import type { ReactNode } from 'react';

import type { Metadata } from 'next';

import AppProvider from '@/providers/AppProvider';
import { Analytics } from '@vercel/analytics/next';

import { getLocale } from 'next-intl/server';

export const metadata: Metadata = {
    title: 'next base structure',
    description:
        'next base structure Generated by create next app - tailwind - next-intl - next-themes - nextjs-toploader - typescript '
};

const Layout = async ({ children }: Readonly<{ children: ReactNode }>) => {
    const locale = await getLocale();
    const dir = locale === 'ar' ? 'rtl' : 'ltr';

    return (
        <html suppressHydrationWarning lang={locale} dir={dir}>
            <body className={`bg-background text-foreground relative overflow-x-clip antialiased`}>
                <AppProvider>
                    {children}
                    <Analytics />
                </AppProvider>
            </body>
        </html>
    );
};

export default Layout;
